import { ImBook, ImArrowRight, ImFire } from 'react-icons/im'
import { WiRain } from 'react-icons/wi'
import { GiFlowerPot } from 'react-icons/gi'
import { FaFish, FaMountain } from 'react-icons/fa'

export const KanjiTable = [
    {
        title: 'book',
        pair: '01',
        kanji: '本',
        icon: { ImBook },
        translation: 'Książka',
        img: require('./../../../img/book_kanji.svg').default,
    },
    {
        title: 'right',
        pair: '02',
        kanji: '右',
        icon: { ImArrowRight },
        translation: 'Prawo (kierunek)',
        img: require('./../../../img/right_kanji.svg').default,
    },
    {
        title: 'rain',
        pair: '03',
        kanji: '雨',
        icon: { WiRain },
        translation: 'Deszcz',
        img: require('./../../../img/rain_kanji.svg').default,
    },
    {
        title: 'fire',
        pair: '04',
        kanji: '火',
        icon: { ImFire },
        translation: 'Ogień',
        img: require('./../../../img/fire_kanji.svg').default,
    },
    {
        title: 'gold',
        pair: '05',
        kanji: '金',
        // icon: { GiGoldbar },
        translation: 'Książka',
        img: require('./../../../img/gold_kanji.svg').default,
    },
    {
        title: 'flower',
        pair: '06',
        kanji: '花',
        icon: { GiFlowerPot },
        translation: 'Kwiat',
        img: require('./../../../img/flower_kanji.svg').default,
    },
    {
        title: 'fish',
        pair: '07',
        kanji: '魚',
        icon: { FaFish },
        translation: 'Ryba',
        img: require('./../../../img/fish_kanji.svg').default,
    },
    {
        title: 'mountain',
        pair: '08',
        kanji: '山',
        icon: { FaMountain },
        translation: 'Góra',
        img: require('./../../../img/mountain_kanji.svg').default,
    },
    {
        title: 'book',
        pair: '01',
        kanji: '本',
        icon: { ImBook },
        translation: 'Książka',
        img: require('./../../../img/book.svg').default,
    },
    {
        title: 'right',
        pair: '02',
        kanji: '右',
        icon: { ImArrowRight },
        translation: 'Prawo (kierunek)',
        img: require('./../../../img/right.svg').default,
    },
    {
        title: 'rain',
        pair: '03',
        kanji: '雨',
        icon: { WiRain },
        translation: 'Deszcz',
        img: require('./../../../img/rain.svg').default,
    },
    {
        title: 'fire',
        pair: '04',
        kanji: '火',
        icon: { ImFire },
        translation: 'Ogień',
        img: require('./../../../img/fire.svg').default,
    },
    {
        title: 'gold',
        pair: '05',
        kanji: '金',
        // icon: { GiGoldbar },
        translation: 'Książka',
        img: require('./../../../img/gold.svg').default,
    },
    {
        title: 'flower',
        pair: '06',
        kanji: '花',
        icon: { GiFlowerPot },
        translation: 'Kwiat',
        img: require('./../../../img/flowers.svg').default,
    },
    {
        title: 'fish',
        pair: '07',
        kanji: '魚',
        icon: { FaFish },
        translation: 'Ryba',
        img: require('./../../../img/fish.svg').default,
    },
    {
        title: 'mountain',
        pair: '08',
        kanji: '山',
        icon: { FaMountain },
        translation: 'Góra',
        img: require('./../../../img/mountain.svg').default,
    },

]